/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrames;

import DataEnteringFrames.*;
import MyConn.MyConn;
import SubFrames.GRNForDueFrame;
import SubFrames.SetNeedItemsFrame;
import SubFrames.SetSupplyingItems;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.Time;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.hadoop.hive.ql.parse.HiveParser;

/**
 *
 * @author Nuwantha
 */
public class DataEnteringFrames extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form LogInFrame
     */
    public DataEnteringFrames() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Icon.jpg")));

        Services.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Services.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Stock.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Stock.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Staff.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Staff.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Income.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Income.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Expence.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Expence.jpg")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Professions.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Professions.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        DueFinishing.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Due.png")).getScaledInstance(180, 130, Image.SCALE_SMOOTH)));
        Suppliers.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Suppliers.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        IncomeExpenceReasons.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/IncomeExpenceReasons.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Customers.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Customers.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Users.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/User.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        GRN.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/GRN.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        SalaryPaying.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/SalaryPaying.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        StaffAttending.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/StaffAttending.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        DueFinishing = new javax.swing.JLabel();
        Income = new javax.swing.JLabel();
        Expence = new javax.swing.JLabel();
        Stock = new javax.swing.JLabel();
        Staff = new javax.swing.JLabel();
        Customers = new javax.swing.JLabel();
        Suppliers = new javax.swing.JLabel();
        Professions = new javax.swing.JLabel();
        Services = new javax.swing.JLabel();
        IncomeExpenceReasons = new javax.swing.JLabel();
        Users = new javax.swing.JLabel();
        SalaryPaying = new javax.swing.JLabel();
        StaffAttending = new javax.swing.JLabel();
        GRN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel3KeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("-");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Data Entering");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X ");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        Description.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Description.setForeground(new java.awt.Color(255, 255, 255));
        Description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        DueFinishing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DueFinishing.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        DueFinishing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DueFinishingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DueFinishingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DueFinishingMouseExited(evt);
            }
        });

        Income.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Income.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        Income.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IncomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IncomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IncomeMouseExited(evt);
            }
        });

        Expence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Expence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        Expence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpenceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExpenceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExpenceMouseExited(evt);
            }
        });

        Stock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Stock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        Stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StockMouseExited(evt);
            }
        });

        Staff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Staff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        Staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StaffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StaffMouseExited(evt);
            }
        });

        Customers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Customers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        Customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CustomersMouseExited(evt);
            }
        });

        Suppliers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Suppliers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        Suppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SuppliersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SuppliersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SuppliersMouseExited(evt);
            }
        });

        Professions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Professions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        Professions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfessionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProfessionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProfessionsMouseExited(evt);
            }
        });

        Services.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Services.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        Services.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServicesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ServicesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ServicesMouseExited(evt);
            }
        });

        IncomeExpenceReasons.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IncomeExpenceReasons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        IncomeExpenceReasons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IncomeExpenceReasonsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IncomeExpenceReasonsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IncomeExpenceReasonsMouseExited(evt);
            }
        });

        Users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Users.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsersMouseExited(evt);
            }
        });

        SalaryPaying.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SalaryPaying.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        SalaryPaying.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalaryPayingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalaryPayingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalaryPayingMouseExited(evt);
            }
        });

        StaffAttending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StaffAttending.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        StaffAttending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StaffAttendingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StaffAttendingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StaffAttendingMouseExited(evt);
            }
        });

        GRN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GRN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        GRN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GRNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GRNMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(DueFinishing, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Income, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Expence, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(IncomeExpenceReasons, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(Professions, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Services, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(SalaryPaying, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(StaffAttending, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(Suppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Customers, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Staff, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GRN, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Customers, DueFinishing, Expence, GRN, Income, IncomeExpenceReasons, Professions, SalaryPaying, Services, Staff, StaffAttending, Stock, Suppliers, Users});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DueFinishing, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Income, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Expence, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Suppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Customers, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StaffAttending, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GRN, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Services, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IncomeExpenceReasons, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SalaryPaying, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Professions, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Staff, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Customers, DueFinishing, Expence, GRN, Income, IncomeExpenceReasons, Professions, SalaryPaying, Services, Staff, StaffAttending, Stock, Suppliers, Users});

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(881, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel3KeyPressed
    }//GEN-LAST:event_jPanel3KeyPressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void DueFinishingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DueFinishingMouseClicked
        DueFinishingFrame frame = new DueFinishingFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_DueFinishingMouseClicked

    private void DueFinishingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DueFinishingMouseEntered
        DueFinishing.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Due.png")).getScaledInstance(200, 150, Image.SCALE_SMOOTH)));
        Description.setText("Enter Due Finishing Details");
    }//GEN-LAST:event_DueFinishingMouseEntered

    private void DueFinishingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DueFinishingMouseExited
        DueFinishing.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Due.png")).getScaledInstance(180, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);
    }//GEN-LAST:event_DueFinishingMouseExited

    private void IncomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IncomeMouseClicked
        IncomeFrame frame = new IncomeFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_IncomeMouseClicked

    private void IncomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IncomeMouseExited
        Income.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Income.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);
    }//GEN-LAST:event_IncomeMouseExited

    private void IncomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IncomeMouseEntered
        Income.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Income.png")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter Income Details");
    }//GEN-LAST:event_IncomeMouseEntered

    private void ExpenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpenceMouseClicked
        ExpenceFrame frame = new ExpenceFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_ExpenceMouseClicked

    private void ExpenceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpenceMouseExited
        Expence.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Expence.jpg")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);
    }//GEN-LAST:event_ExpenceMouseExited

    private void ExpenceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpenceMouseEntered
        Expence.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Expence.jpg")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter Expence Details");
    }//GEN-LAST:event_ExpenceMouseEntered

    private void StockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMouseClicked
        StockFrame frame = new StockFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_StockMouseClicked

    private void StockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMouseExited
        Stock.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Stock.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);
    }//GEN-LAST:event_StockMouseExited

    private void StockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMouseEntered
        Stock.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Stock.png")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter Stock Details");
    }//GEN-LAST:event_StockMouseEntered

    private void StaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffMouseClicked
        StaffFrame frame = new StaffFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_StaffMouseClicked

    private void StaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffMouseExited
        Staff.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Staff.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);
    }//GEN-LAST:event_StaffMouseExited

    private void StaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffMouseEntered
        Staff.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Staff.png")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter Staff Details");
    }//GEN-LAST:event_StaffMouseEntered

    private void CustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomersMouseClicked
        CustomerFrame frame = new CustomerFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_CustomersMouseClicked

    private void CustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomersMouseExited
        Customers.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Customers.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);
    }//GEN-LAST:event_CustomersMouseExited

    private void CustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomersMouseEntered
        Customers.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Customers.png")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter Customer Details");
    }//GEN-LAST:event_CustomersMouseEntered

    private void SuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuppliersMouseClicked
        SuppliersFrame frame = new SuppliersFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_SuppliersMouseClicked

    private void SuppliersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuppliersMouseExited
        Suppliers.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Suppliers.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);

    }//GEN-LAST:event_SuppliersMouseExited

    private void SuppliersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuppliersMouseEntered
        Suppliers.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Suppliers.png")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter Suppliers Details");
    }//GEN-LAST:event_SuppliersMouseEntered

    private void ProfessionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfessionsMouseClicked
        ProfessionsFrame frame = new ProfessionsFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_ProfessionsMouseClicked

    private void ProfessionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfessionsMouseExited
        Professions.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Professions.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);

    }//GEN-LAST:event_ProfessionsMouseExited

    private void ProfessionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfessionsMouseEntered
        Professions.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Professions.png")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter Professions Details");
    }//GEN-LAST:event_ProfessionsMouseEntered

    private void IncomeExpenceReasonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IncomeExpenceReasonsMouseClicked
        IncomeExpenceReasonsFrame frame = new IncomeExpenceReasonsFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_IncomeExpenceReasonsMouseClicked

    private void IncomeExpenceReasonsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IncomeExpenceReasonsMouseExited
        IncomeExpenceReasons.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/IncomeExpenceReasons.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);

    }//GEN-LAST:event_IncomeExpenceReasonsMouseExited

    private void IncomeExpenceReasonsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IncomeExpenceReasonsMouseEntered
        IncomeExpenceReasons.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/IncomeExpenceReasons.png")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter Income And Expence Reasons Details");
    }//GEN-LAST:event_IncomeExpenceReasonsMouseEntered

    private void UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseClicked
        UsersFrame frame = new UsersFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_UsersMouseClicked

    private void UsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseExited
        Users.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/User.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);
    }//GEN-LAST:event_UsersMouseExited

    private void UsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseEntered
        Users.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/User.png")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter Users Details");
    }//GEN-LAST:event_UsersMouseEntered

    private void GRNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNMouseClicked
        GRNFrame frame = new GRNFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_GRNMouseClicked

    private void GRNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNMouseExited
        GRN.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/GRN.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);
    }//GEN-LAST:event_GRNMouseExited

    private void GRNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNMouseEntered
        GRN.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/GRN.png")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter GRN Details");
    }//GEN-LAST:event_GRNMouseEntered

    private void ServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicesMouseClicked
        ServicesFrame frame = new ServicesFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_ServicesMouseClicked

    private void ServicesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicesMouseExited
        Services.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Services.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);
    }//GEN-LAST:event_ServicesMouseExited

    private void ServicesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicesMouseEntered
        Services.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Services.png")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter Services Details");
    }//GEN-LAST:event_ServicesMouseEntered

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        Description.setText(null);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void SalaryPayingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalaryPayingMouseClicked
        SalaryPayingFrame frame = new SalaryPayingFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_SalaryPayingMouseClicked

    private void SalaryPayingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalaryPayingMouseExited
        SalaryPaying.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/SalaryPaying.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);
    }//GEN-LAST:event_SalaryPayingMouseExited

    private void SalaryPayingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalaryPayingMouseEntered
        SalaryPaying.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/SalaryPaying.png")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter Salary Paying Details");
    }//GEN-LAST:event_SalaryPayingMouseEntered

    private void StaffAttendingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffAttendingMouseClicked
        StaffAttendingFrame frame = new StaffAttendingFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_StaffAttendingMouseClicked

    private void StaffAttendingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffAttendingMouseExited
        StaffAttending.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/StaffAttending.png")).getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        Description.setText(null);
    }//GEN-LAST:event_StaffAttendingMouseExited

    private void StaffAttendingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffAttendingMouseEntered
        StaffAttending.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/StaffAttending.png")).getScaledInstance(160, 160, Image.SCALE_SMOOTH)));
        Description.setText("Enter Staff Attending Details");
    }//GEN-LAST:event_StaffAttendingMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataEnteringFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataEnteringFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataEnteringFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataEnteringFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DataEnteringFrames().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Customers;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel DueFinishing;
    private javax.swing.JLabel Expence;
    private javax.swing.JLabel GRN;
    private javax.swing.JLabel Income;
    private javax.swing.JLabel IncomeExpenceReasons;
    private javax.swing.JLabel Professions;
    private javax.swing.JLabel SalaryPaying;
    private javax.swing.JLabel Services;
    private javax.swing.JLabel Staff;
    private javax.swing.JLabel StaffAttending;
    private javax.swing.JLabel Stock;
    private javax.swing.JLabel Suppliers;
    private javax.swing.JLabel Users;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
