/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrames;

import DataEnteringFrames.GRNFrame;
import MyConn.MyConn;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Array;
import java.net.URL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Nuwantha
 */
public class MainFrame extends javax.swing.JFrame {

    int xMouse, yMouse;
    Font maxFont = new Font("Tahoma", Font.BOLD, 25);
    Font minFont = new Font("Tahoma", Font.BOLD, 20);

    /**
     * Creates new form LogInFrame
     */
    public MainFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Icon.jpg")));

        this.setLocation(0, 0);

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);
        NotificationCenter.setOpaque(false);
        NotificationCenter.setBackground(new Color(0, 0, 0, 30));

        LogOut.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Logout.png")).getScaledInstance(163 - 10, 146, Image.SCALE_SMOOTH)));
        LogOut.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Logout.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        PosSystem.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/POS.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        GRN.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/GRN.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        Details.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Details.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        Reports.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Report.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        BarcodeGenarator.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Barcode.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        Backup.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Backup.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        Summary.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Summary.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        DataEntering.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/DataEntering.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        SendEMails.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/GMail.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        charts.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Chart.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        QRCodeGenarator.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/QRCode.jpg")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        refresh.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Refresh.png")).getScaledInstance(25, 25, Image.SCALE_SMOOTH)));

        Toolkit tk = Toolkit.getDefaultToolkit();
        this.setSize((int) tk.getScreenSize().getWidth(), (int) tk.getScreenSize().getHeight());

        int width = 450;
        int height = 330;
        jLabel2.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Wallpaper.jpg")).getScaledInstance(width, height, Image.SCALE_SMOOTH)));

        setNotifications();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NotificationCenter = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        Details = new javax.swing.JLabel();
        Reports = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        Backup = new javax.swing.JLabel();
        BarcodeGenarator = new javax.swing.JLabel();
        Summary = new javax.swing.JLabel();
        PosSystem = new javax.swing.JLabel();
        DataEntering = new javax.swing.JLabel();
        GRN = new javax.swing.JLabel();
        SendEMails = new javax.swing.JLabel();
        charts = new javax.swing.JLabel();
        QRCodeGenarator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel3KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Menu");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X ");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("-");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(361, 361, 361)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(215, 694));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        NotificationCenter.setColumns(20);
        NotificationCenter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NotificationCenter.setForeground(new java.awt.Color(255, 255, 255));
        NotificationCenter.setRows(5);
        NotificationCenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        NotificationCenter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NotificationCenter.setFocusable(false);
        NotificationCenter.setMaximumSize(new java.awt.Dimension(250, 800));
        NotificationCenter.setRequestFocusEnabled(false);
        NotificationCenter.setSelectionColor(new java.awt.Color(0, 51, 204));
        NotificationCenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NotificationCenterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NotificationCenterMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(NotificationCenter);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jLabel2.setMaximumSize(new java.awt.Dimension(250, 500));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 200));

        refresh.setBackground(new java.awt.Color(255, 255, 51));
        refresh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        refresh.setForeground(new java.awt.Color(204, 255, 255));
        refresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refresh.setText("Refresh");
        refresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        Details.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Details.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DetailsMouseExited(evt);
            }
        });

        Reports.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        Reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportsMouseExited(evt);
            }
        });

        LogOut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutMouseExited(evt);
            }
        });

        Backup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Backup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Backup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        Backup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackupMouseExited(evt);
            }
        });

        BarcodeGenarator.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BarcodeGenarator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BarcodeGenarator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        BarcodeGenarator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarcodeGenaratorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BarcodeGenaratorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BarcodeGenaratorMouseExited(evt);
            }
        });

        Summary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Summary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Summary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        Summary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SummaryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SummaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SummaryMouseExited(evt);
            }
        });

        PosSystem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PosSystem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PosSystem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        PosSystem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PosSystemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PosSystemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PosSystemMouseExited(evt);
            }
        });

        DataEntering.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DataEntering.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DataEntering.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        DataEntering.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataEnteringMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataEnteringMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DataEnteringMouseExited(evt);
            }
        });

        GRN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GRN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GRN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        GRN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GRNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GRNMouseExited(evt);
            }
        });

        SendEMails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SendEMails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SendEMails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        SendEMails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendEMailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SendEMailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SendEMailsMouseExited(evt);
            }
        });

        charts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        charts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        charts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        charts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chartsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chartsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chartsMouseExited(evt);
            }
        });

        QRCodeGenarator.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        QRCodeGenarator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QRCodeGenarator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        QRCodeGenarator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QRCodeGenaratorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QRCodeGenaratorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QRCodeGenaratorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PosSystem, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(Summary, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(Backup, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(DataEntering, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(BarcodeGenarator, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QRCodeGenarator, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(SendEMails, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Reports, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GRN, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(Details, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(charts, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))))
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(PosSystem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(GRN, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(charts, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(Details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DataEntering, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Summary, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(SendEMails, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(Reports, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QRCodeGenarator, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(BarcodeGenarator, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(Backup, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        jScrollPane2.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(14, 14, 14)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1024, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3KeyPressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Frame[] frames = MainFrame.getFrames();
        for (int i = 0; i < frames.length; i++) {
            frames[i].dispose();
        }
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void ReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseExited
        Reports.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Report.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        jLabel14.setText(null);
    }//GEN-LAST:event_ReportsMouseExited

    private void ReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseEntered
        Reports.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Report.png")).getScaledInstance(183, 177, Image.SCALE_SMOOTH)));
        jLabel14.setText("Reports");
    }//GEN-LAST:event_ReportsMouseEntered

    private void LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseExited
        LogOut.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Logout.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        jLabel14.setText(null);
    }//GEN-LAST:event_LogOutMouseExited

    private void LogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseEntered
        LogOut.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Logout.png")).getScaledInstance(183, 177, Image.SCALE_SMOOTH)));
        jLabel14.setText("Log Out");
    }//GEN-LAST:event_LogOutMouseEntered

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        Frame[] frames = MainFrame.getFrames();
        for (int i = 0; i < frames.length; i++) {
            frames[i].dispose();
        }
        this.dispose();
        LogInFrame frame = new LogInFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_LogOutMouseClicked

    private void BackupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackupMouseExited
        Backup.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Backup.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        jLabel14.setText(null);
    }//GEN-LAST:event_BackupMouseExited

    private void BackupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackupMouseEntered
        Backup.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Backup.png")).getScaledInstance(183, 177, Image.SCALE_SMOOTH)));
        jLabel14.setText("Backup");
    }//GEN-LAST:event_BackupMouseEntered

    private void BarcodeGenaratorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarcodeGenaratorMouseExited
        BarcodeGenarator.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Barcode.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        jLabel14.setText(null);
    }//GEN-LAST:event_BarcodeGenaratorMouseExited

    private void BarcodeGenaratorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarcodeGenaratorMouseEntered
        BarcodeGenarator.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Barcode.png")).getScaledInstance(183, 177, Image.SCALE_SMOOTH)));
        jLabel14.setText("Barcode Genarator");
    }//GEN-LAST:event_BarcodeGenaratorMouseEntered

    private void SummaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SummaryMouseExited
        Summary.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Summary.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        jLabel14.setText(null);
    }//GEN-LAST:event_SummaryMouseExited

    private void SummaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SummaryMouseEntered
        Summary.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Summary.png")).getScaledInstance(183, 177, Image.SCALE_SMOOTH)));
        jLabel14.setText("Summary");
    }//GEN-LAST:event_SummaryMouseEntered

    private void DetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailsMouseExited
        Details.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Details.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        jLabel14.setText(null);
    }//GEN-LAST:event_DetailsMouseExited

    private void DetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailsMouseEntered
        Details.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Details.png")).getScaledInstance(183, 177, Image.SCALE_SMOOTH)));
        jLabel14.setText("Details");
    }//GEN-LAST:event_DetailsMouseEntered

    private void GRNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNMouseExited
        GRN.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/GRN.png")).getScaledInstance(153, 147, Image.SCALE_SMOOTH)));
        jLabel14.setText(null);
    }//GEN-LAST:event_GRNMouseExited

    private void GRNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNMouseEntered
        GRN.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/GRN.png")).getScaledInstance(183, 177, Image.SCALE_SMOOTH)));
        jLabel14.setText("GRN");
    }//GEN-LAST:event_GRNMouseEntered

    private void PosSystemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosSystemMouseEntered
        PosSystem.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/POS.png")).getScaledInstance(183, 177, Image.SCALE_SMOOTH)));
        jLabel14.setText("POS System");
    }//GEN-LAST:event_PosSystemMouseEntered

    private void PosSystemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosSystemMouseExited
        PosSystem.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/POS.png")).getScaledInstance(153, 147, Image.SCALE_SMOOTH)));
        jLabel14.setText(null);
    }//GEN-LAST:event_PosSystemMouseExited

    private void DataEnteringMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataEnteringMouseExited
        DataEntering.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/DataEntering.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        jLabel14.setText(null);
    }//GEN-LAST:event_DataEnteringMouseExited

    private void DataEnteringMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataEnteringMouseEntered
        DataEntering.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/DataEntering.png")).getScaledInstance(183, 177, Image.SCALE_SMOOTH)));
        jLabel14.setText("Data Entering");
    }//GEN-LAST:event_DataEnteringMouseEntered

    private void SendEMailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendEMailsMouseExited
        SendEMails.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/GMail.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        jLabel14.setText(null);
    }//GEN-LAST:event_SendEMailsMouseExited

    private void SendEMailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendEMailsMouseEntered
        SendEMails.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/GMail.png")).getScaledInstance(183, 177, Image.SCALE_SMOOTH)));
        jLabel14.setText("Send Mails");
    }//GEN-LAST:event_SendEMailsMouseEntered

    private void GRNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNMouseClicked
        GRNFrame frame = new GRNFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_GRNMouseClicked

    private void PosSystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosSystemMouseClicked
        PosFrame frame = new PosFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_PosSystemMouseClicked

    private void DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailsMouseClicked
        DetailsFrames frame = new DetailsFrames();
        frame.setVisible(true);
    }//GEN-LAST:event_DetailsMouseClicked

    private void DataEnteringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataEnteringMouseClicked
        DataEnteringFrames frame = new DataEnteringFrames();
        frame.setVisible(true);
    }//GEN-LAST:event_DataEnteringMouseClicked

    private void SendEMailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendEMailsMouseClicked
        EmailSendingFrame frame = new EmailSendingFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_SendEMailsMouseClicked

    private void ReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseClicked
        ReportFrame frame = new ReportFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_ReportsMouseClicked

    private void chartsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chartsMouseExited
        charts.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Chart.png")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        jLabel14.setText(null);
    }//GEN-LAST:event_chartsMouseExited

    private void chartsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chartsMouseEntered
        charts.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Chart.png")).getScaledInstance(183, 177, Image.SCALE_SMOOTH)));
        jLabel14.setText("Charts");
    }//GEN-LAST:event_chartsMouseEntered

    private void chartsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chartsMouseClicked
        ChartFrame frame = new ChartFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_chartsMouseClicked

    private void BarcodeGenaratorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarcodeGenaratorMouseClicked
        BarcodeGenarator frame = new BarcodeGenarator();
        frame.setVisible(true);
    }//GEN-LAST:event_BarcodeGenaratorMouseClicked

    private void QRCodeGenaratorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QRCodeGenaratorMouseClicked
        QRCodeGenarator frame = new QRCodeGenarator();
        frame.setVisible(true);
    }//GEN-LAST:event_QRCodeGenaratorMouseClicked

    private void QRCodeGenaratorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QRCodeGenaratorMouseExited
        QRCodeGenarator.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/QRCode.jpg")).getScaledInstance(163, 157, Image.SCALE_SMOOTH)));
        jLabel14.setText(null);
    }//GEN-LAST:event_QRCodeGenaratorMouseExited

    private void QRCodeGenaratorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QRCodeGenaratorMouseEntered
        QRCodeGenarator.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/QRCode.jpg")).getScaledInstance(183, 177, Image.SCALE_SMOOTH)));
        jLabel14.setText("QR Code Genarator");
    }//GEN-LAST:event_QRCodeGenaratorMouseEntered

    private void BackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackupMouseClicked
        BackupAndRestore frame = new BackupAndRestore();
        frame.setVisible(true);
    }//GEN-LAST:event_BackupMouseClicked

    private void NotificationCenterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotificationCenterMouseEntered

        new Thread() {

            public void run() {
            }
        }.start();
    }//GEN-LAST:event_NotificationCenterMouseEntered

    private void NotificationCenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotificationCenterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NotificationCenterMouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
    }//GEN-LAST:event_jPanel2MouseExited

    private void refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseEntered
        refresh.setOpaque(true);
        refresh.setBackground(new Color(0, 0, 200));
        refresh.setFont(new Font("Tahoma", Font.BOLD, 21));
        refresh.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Refresh.png")).getScaledInstance(28, 28, Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_refreshMouseEntered

    private void refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseExited
        refresh.setOpaque(false);
        refresh.setBackground(Color.blue);
        refresh.setFont(new Font("Tahoma", Font.BOLD, 18));
        refresh.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Refresh.png")).getScaledInstance(25, 25, Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_refreshMouseExited

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        setNotifications();
    }//GEN-LAST:event_refreshMouseClicked

    private void SummaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SummaryMouseClicked
        SummaryFrame frame = new SummaryFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_SummaryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backup;
    private javax.swing.JLabel BarcodeGenarator;
    private javax.swing.JLabel DataEntering;
    private javax.swing.JLabel Details;
    private javax.swing.JLabel GRN;
    private javax.swing.JLabel LogOut;
    private javax.swing.JTextArea NotificationCenter;
    private javax.swing.JLabel PosSystem;
    private javax.swing.JLabel QRCodeGenarator;
    private javax.swing.JLabel Reports;
    private javax.swing.JLabel SendEMails;
    private javax.swing.JLabel Summary;
    private javax.swing.JLabel charts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel refresh;
    // End of variables declaration//GEN-END:variables
private void setNotifications() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat dateFormat2 = new SimpleDateFormat("EEEE dd MMMM yyyy");
        Date today = new Date();
        Date tomorrow = new Date(today.getYear(), today.getMonth(), today.getDate() + 1);
        try {
            String sql = "select * from stock where inoinstock between 0 and 20 ";
            ResultSet rs = MyConn.search(sql);
            NotificationCenter.setText("\n Stock Low :");
            while (rs.next()) {
                NotificationCenter.setText(NotificationCenter.getText() + "\n   "+rs.getString(1) + " - " + rs.getString(3) + "(" + rs.getString(7) + ")");
            }
            NotificationCenter.setText(NotificationCenter.getText() + "\n----------------------------------------------------------------------------");
            NotificationCenter.setText(NotificationCenter.getText() + "\n Today :  " + dateFormat2.format(today) + " \n  Due Deals With Suppliers :");
            ResultSet getGRNDue = MyConn.search("select dueid,duetype from due where duetype = 1 and duefinishingdate = '" + dateFormat.format(today) + "'  ");
            while (getGRNDue.next()) {
                ResultSet getGRN = MyConn.search("select id,suppliers_sid from grn where due_dueid = '" + getGRNDue.getString(1) + "' ");
                while (getGRN.next()) {
                    ResultSet getSupplier = MyConn.search("select sname from suppliers where sid = '" + getGRN.getString(2) + "' ");
                    while (getSupplier.next()) {
                        NotificationCenter.setText(NotificationCenter.getText() + "\n    (" + getGRNDue.getString(1) + ") ID. " + getGRN.getString(1) + " With " + getGRN.getString(2) + ". " + getSupplier.getString(1) + "");
                    }
                }
            }
            NotificationCenter.setText(NotificationCenter.getText() + "\n  Due Sales With Customers :");
            ResultSet getSalesDue = MyConn.search("select dueid,duetype from due where duetype = 0 and duefinishingdate = '" + dateFormat.format(today) + "'   ");
            while (getSalesDue.next()) {
                ResultSet getSaleDetails = MyConn.search("select invoice,customers_cusid from sales where due_dueid = '" + getSalesDue.getString(1) + "' ");
                while (getSaleDetails.next()) {
                    ResultSet getCustomer = MyConn.search("select cusname from customers where cusid = '" + getSaleDetails.getString(2) + "' ");
                    while (getCustomer.next()) {
                        NotificationCenter.setText(NotificationCenter.getText() + "\n    (" + getSalesDue.getString(1) + ") Invoice. " + getSaleDetails.getString(1) + " With " + getCustomer.getString(1) + "");
                    }
                }
            }
            NotificationCenter.setText(NotificationCenter.getText() + "\n----------------------------------------------------------------------------");

            NotificationCenter.setText(NotificationCenter.getText() + "\n Tomorow :    " + dateFormat2.format(tomorrow) + " ");
            NotificationCenter.setText(NotificationCenter.getText() + "\n  Due Deals With Suppliers :");
            ResultSet getGRNDueTomorrow = MyConn.search("select dueid,duetype from due where duetype = 1 and duefinishingdate = '" + dateFormat.format(tomorrow) + "'  ");
            while (getGRNDueTomorrow.next()) {
                ResultSet getGRN = MyConn.search("select id,suppliers_sid from grn where id = '" + getGRNDueTomorrow.getString(1) + "' ");
                while (getGRN.next()) {
                    ResultSet getSupplier = MyConn.search("select sname from suppliers where sid = '" + getGRN.getString(2) + "' ");
                    while (getSupplier.next()) {
                        NotificationCenter.setText(NotificationCenter.getText() + "\n    (" + getGRNDueTomorrow.getString(1) + ") ID. " + " With " + getGRN.getString(2) + ". " + getSupplier.getString(1) + "");
                    }
                }
            }
            NotificationCenter.setText(NotificationCenter.getText() + "\n  Due Sales With Customers :");
            ResultSet getSalesDueTomorrow = MyConn.search("select dueid,duetype from due where duetype = 0 and duefinishingdate = '" + dateFormat.format(tomorrow) + "'   ");
            while (getSalesDueTomorrow.next()) {
                ResultSet getSaleDetails = MyConn.search("select invoice,customers_cusid from sales where due_dueid = '" + getSalesDueTomorrow.getString(1) + "' ");
                while (getSaleDetails.next()) {
                    ResultSet getCustomer = MyConn.search("select cusname from customers where cusid = '" + getSaleDetails.getString(2) + "' ");
                    while (getCustomer.next()) {
                        NotificationCenter.setText(NotificationCenter.getText() + "\n    (" + getSalesDueTomorrow.getString(1) + ") Invoice. " + getSaleDetails.getString(1) + " With " + getCustomer.getString(1) + "");
                    }
                }
            }
            NotificationCenter.setText(NotificationCenter.getText() + "\n----------------------------------------------------------------------------");
            NotificationCenter.setText(NotificationCenter.getText() + "\n Previous :    ");
            NotificationCenter.setText(NotificationCenter.getText() + "\n  Due Deals With Suppliers :");
            ResultSet getGRNDueOther = MyConn.search("select dueid,duetype,duefinishingdate from due where duetype = 1 and duefinisheddate is null");
            while (getGRNDueOther.next()) {
                Date dueDate = new Date(getGRNDueOther.getDate(3).getTime());
                if (dueDate.before(today)) {
                    if (!dateFormat.format(dueDate).equals(dateFormat.format(today))) {
                        ResultSet getGRN = MyConn.search("select id,suppliers_sid from grn where due_dueid = '" + getGRNDueOther.getString(1) + "' ");
                        while (getGRN.next()) {
                            ResultSet getSupplier = MyConn.search("select sname from suppliers where sid = '" + getGRN.getString(2) + "' ");
                            while (getSupplier.next()) {
                                NotificationCenter.setText(NotificationCenter.getText() + "\n    (" + getGRNDueOther.getString(1) + ") ID. " + getGRN.getString(1) + " With " + getGRN.getString(2) + ". " + getSupplier.getString(1) + "    " + dateFormat.format(dueDate) + "");
                            }
                        }
                    }
                }

            }
            NotificationCenter.setText(NotificationCenter.getText() + "\n  Due Sales With Customers :");
            ResultSet getSalesDueOther = MyConn.search("select dueid,duetype,duefinishingdate from due where duetype = 0 and duefinisheddate is null ");
            while (getSalesDueOther.next()) {
                Date dueDate = new Date(getSalesDueOther.getDate(3).getTime());
                if (dueDate.before(today)) {
                    if (!dateFormat.format(dueDate).equals(dateFormat.format(today))) {
                        ResultSet getSaleDetails = MyConn.search("select invoice,customers_cusid from sales where due_dueid = '" + getSalesDueOther.getString(1) + "' ");
                        while (getSaleDetails.next()) {
                            ResultSet getCustomer = MyConn.search("select cusname from customers where cusid = '" + getSaleDetails.getString(2) + "' ");
                            while (getCustomer.next()) {
                                NotificationCenter.setText(NotificationCenter.getText() + "\n    (" + getSalesDueOther.getString(1) + ") Invoice. " + getSaleDetails.getString(1) + " With " + getCustomer.getString(1) + "    " + dateFormat.format(dueDate) + "");
                            }
                        }
                    }

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jScrollPane1.getHorizontalScrollBar().setValue(jScrollPane1.getHorizontalScrollBar().getMinimum());
    }
}
