/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ReportFrames;

import DetailsFrames.*;
import DataEnteringFrames.StaffFrame;
import MyConn.MyConn;
import SubFrames.MoreSalesDetailsFrame;
import SubFrames.PrintingFrame;
import datechooser.beans.DateChooserCombo;
import java.awt.*;
import java.awt.event.*;
import java.io.InputStream;
import java.lang.reflect.Array;
import java.net.URL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.xml.JasperDesignFactory;
import net.sf.jasperreports.engine.xml.JasperPrintFactory;
import net.sf.jasperreports.view.JasperDesignViewer;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.web.servlets.JasperPrintAccessor;
import org.springframework.ui.jasperreports.JasperReportsUtils;

/**
 *
 * @author Nuwantha
 */
public class SalesReport extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form LogInFrame
     */
    public SalesReport() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Icon.jpg")));
        jTable1.getTableHeader().setFont(new Font("Tahome", Font.PLAIN, 18));
        jTable1.setRowHeight(30);
        Print.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Print.png")).getScaledInstance(30, 28, Image.SCALE_SMOOTH)));
        Search.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Search.png")).getScaledInstance(30, 28, Image.SCALE_SMOOTH)));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        Print = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Discount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel3KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Sales Details");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X ");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("-");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        Search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice", "Date", "Time", "Customer", "Staff Member", "Discount", "Discount Percentage", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "ID", "Date", "Time", "Customer", "Staff Member", "Discount", "Total" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Search By :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Order By :");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "ID", "Date", "Time", "Customer", "Staff Member", "Discount", "Total" }));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ascending", "Descending" }));

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Discount", "Total" }));

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "More Than", "Less Than", "Between" }));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("And");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("From");

        dateChooserCombo1.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 18));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("To");

        dateChooserCombo2.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 18));

        Print.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Total Income    :");

        Total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Total.setText("0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Total Discount   :");

        Discount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Discount.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(22, 22, 22)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jComboBox2)
                    .addComponent(jComboBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-938)/2, (screenSize.height-630)/2, 938, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3KeyPressed(KeyEvent evt) {//GEN-FIRST:event_jPanel3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3KeyPressed

    private void jPanel3MousePressed(MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jLabel5MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel11MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void SearchActionPerformed(ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        java.sql.Date first = new java.sql.Date(dateChooserCombo1.getSelectedDate().getTimeInMillis());
        java.sql.Date second = new java.sql.Date(dateChooserCombo2.getSelectedDate().getTimeInMillis());
        String sql = "select * from sales  where date between '" + first + "' and '" + second + "' ";
        String order = "asc";
        String orderType = "";
        if (jComboBox3.getSelectedIndex() == 0) {
            order = "asc";
        } else {
            order = "desc";
        }
        if (jComboBox2.getSelectedIndex() == 0) {
            sql = "select * from sales where date between '" + first + "' and '" + second + "' ";
        } else if (jComboBox2.getSelectedIndex() == 1) {
            orderType = "invoice";
        } else if (jComboBox2.getSelectedIndex() == 2) {
            orderType = "date";
        } else if (jComboBox2.getSelectedIndex() == 3) {
            orderType = "time";
        } else if (jComboBox2.getSelectedIndex() == 4) {
            orderType = "customers_cusid";
        } else if (jComboBox2.getSelectedIndex() == 5) {
            orderType = "staff_sid";
        } else if (jComboBox2.getSelectedIndex() == 6) {
            orderType = "discount";
        } else if (jComboBox2.getSelectedIndex() == 7) {
            orderType = "total";
        }

        if (jComboBox5.getSelectedIndex() == 0) {
            if (jComboBox2.getSelectedIndex() == 0) {
                sql = "select * from sales where date between '" + first + "' and '" + second + "'";
            } else {
                sql = sql + " order by " + orderType + "  " + order + "  ";
            }
        } else {
            if (jComboBox5.getSelectedIndex() == 3) {
                if (jComboBox2.getSelectedIndex() == 0) {
                    sql = sql + " and " + jComboBox4.getSelectedItem().toString() + " between " + jTextField3.getText() + " and " + jTextField4.getText() + "  ";
                } else {
                    sql = sql + " and " + jComboBox4.getSelectedItem().toString() + " between " + jTextField3.getText() + " and " + jTextField4.getText() + "  order by " + orderType + "  " + order + " ";
                }
            } else {
                String than = "";
                if (jComboBox5.getSelectedIndex() == 1) {
                    than = "not";
                }
                if (jComboBox2.getSelectedIndex() == 0) {
                    sql = sql + " and " + jComboBox4.getSelectedItem().toString() + " " + than + " between 0 and " + jTextField3.getText() + " ";
                } else {
                    sql = sql + " and " + jComboBox4.getSelectedItem().toString() + " " + than + " between 0 and " + jTextField3.getText() + " order by " + orderType + "  " + order + "  ";
                }


            }
        }

        try {
            ResultSet rs = MyConn.search(sql);
            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            int x = df.getRowCount();
            for (int i = 0; i < x; i++) {
                df.removeRow(0);
            }
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                String sql2 = "select cusid,cusname from customers where cusid = '" + rs.getString(2) + "' ";
                ResultSet rs2 = MyConn.search(sql2);
                while (rs2.next()) {
                    v.add(rs2.getString(1) + " - " + rs2.getString(2));
                }
                String sql3 = "select sid,sfirstname,slastname from staff where sid = '" + rs.getString(5) + "' ";
                ResultSet rs3 = MyConn.search(sql3);
                while (rs3.next()) {
                    v.add(rs3.getString(1) + " - " + rs3.getString(2) + " " + rs3.getString(3));
                }
                v.add(rs.getString(6));
                String discountPercentage = rs.getDouble(6) * 100 / rs.getDouble(7) + "";
                v.add(discountPercentage.substring(0, 3) + " %");
                v.add(rs.getString(7));
                df.addRow(v);
            }
            String sql2 = "select sum(total) "+sql.substring(sql.indexOf("*")+1);
            ResultSet rs2 = MyConn.search(sql2);
            while (rs2.next()) {                
                Total.setText(rs2.getString(1));
            }
            String sql3 = "select sum(discount) "+sql.substring(sql.indexOf("*")+1);
            ResultSet rs3 = MyConn.search(sql3);
            while (rs3.next()) {                
                Discount.setText(rs3.getString(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void jTable1MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        MoreSalesDetailsFrame frame = new MoreSalesDetailsFrame();
        frame.setVisible(true);
        frame.Invoice.setText(jTable1.getValueAt(row, 0).toString());
        frame.jLabel6.setText(jTable1.getValueAt(row, 1).toString());
        frame.jLabel8.setText(jTable1.getValueAt(row, 2).toString());
        frame.jLabel17.setText(jTable1.getValueAt(row, 3).toString());
        frame.jLabel18.setText(jTable1.getValueAt(row, 4).toString());
        frame.jLabel10.setText(jTable1.getValueAt(row, 5).toString());
        frame.jLabel13.setText(jTable1.getValueAt(row, 6).toString());
        frame.jLabel15.setText(jTable1.getValueAt(row, 7).toString());
        DefaultTableModel df = (DefaultTableModel) frame.jTable1.getModel();

        try {
            String sql1 = "select * from sales_need_stock where sales_invoice = '" + jTable1.getValueAt(row, 0).toString() + "' ";
            ResultSet rs1 = MyConn.search(sql1);
            while (rs1.next()) {
                Vector v = new Vector();
                v.add(rs1.getString(2));
                String sql4 = "select iid,iname from stock where iid = '" + rs1.getString(3) + "' ";
                ResultSet rs4 = MyConn.search(sql4);
                while (rs4.next()) {
                    v.add(rs4.getString(1) + " - " + rs4.getString(2));
                }
                v.add(rs1.getString(4));
                df.addRow(v);
            }
            String sql5 = "select * from sales_has_services where sales_invoice = '" + jTable1.getValueAt(row, 0).toString() + "' ";
            ResultSet rs5 = MyConn.search(sql5);
            while (rs5.next()) {
                Vector v2 = new Vector();
                v2.add(rs5.getString(2));
                String sql4 = "select serid,sername from services where serid = '" + rs5.getString(3) + "' ";
                ResultSet rs4 = MyConn.search(sql4);
                while (rs4.next()) {
                    v2.add(rs4.getString(1) + " - " + rs4.getString(2));
                }
                v2.add(rs5.getString(4));
                df.addRow(v2);
            }
            String sql0 = "select due_dueid from sales where invoice = '" + jTable1.getValueAt(row, 0).toString() + "' ";
            ResultSet rs0 = MyConn.search(sql0);
            while (rs0.next()) {
                String duedata = "select * from due where dueid = '" + rs0.getString(1) + "' ";
                ResultSet due = MyConn.search(duedata);
                while (due.next()) {
                    frame.Due.setText(due.getString(1));
                    frame.DueFinishingDate.setText(due.getString(3));
                    frame.DueFinishedDate.setText(due.getString(4));
                    frame.DueFinishedTime.setText(due.getString(5));
                }
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField2KeyReleased(KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        java.sql.Date first = new java.sql.Date(dateChooserCombo1.getSelectedDate().getTimeInMillis());
        java.sql.Date second = new java.sql.Date(dateChooserCombo2.getSelectedDate().getTimeInMillis());
        String sql = "select * from sales where date between '" + first + "' and '" + second + "' ";
        String order = "asc";
        String orderType = "";
        String order2 = "";
        if (jComboBox3.getSelectedIndex() == 0) {
            order = "asc";
        } else {
            order = "desc";
        }
        if (jComboBox2.getSelectedIndex() == 0) {
            sql = "select * from sales where date between '" + first + "' and '" + second + "' ";
        } else if (jComboBox2.getSelectedIndex() == 1) {
            orderType = "invoice";
        } else if (jComboBox2.getSelectedIndex() == 2) {
            orderType = "date";
        } else if (jComboBox2.getSelectedIndex() == 3) {
            orderType = "time";
        } else if (jComboBox2.getSelectedIndex() == 4) {
            orderType = "customers_cusid";
        } else if (jComboBox2.getSelectedIndex() == 5) {
            orderType = "staff_sid";
        } else if (jComboBox2.getSelectedIndex() == 6) {
            orderType = "discount";
        } else if (jComboBox2.getSelectedIndex() == 7) {
            orderType = "total";
        }
        if (jComboBox1.getSelectedIndex() == 0) {
            sql = "select * from sales where date between '" + first + "' and '" + second + "' ";
        } else if (jComboBox1.getSelectedIndex() == 1) {
            order2 = "invoice";
        } else if (jComboBox1.getSelectedIndex() == 2) {
            order2 = "date";
        } else if (jComboBox1.getSelectedIndex() == 3) {
            order2 = "time";
        } else if (jComboBox1.getSelectedIndex() == 4) {
            order2 = "customers_cusid";
        } else if (jComboBox1.getSelectedIndex() == 5) {
            order2 = "staff_sid";
        } else if (jComboBox1.getSelectedIndex() == 6) {
            order2 = "discount";
        } else if (jComboBox1.getSelectedIndex() == 7) {
            order2 = "total";
        }
        if (jComboBox2.getSelectedIndex() == 0) {
            sql = "select * from sales where date between '" + first + "' and '" + second + "' ";
        } else {
            sql = sql + "and " + order2 + " like '" + jTextField2.getText() + "%' order by " + orderType + "  " + order + " ";
        }

        try {
            ResultSet rs = MyConn.search(sql);
            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            int x = df.getRowCount();
            for (int i = 0; i < x; i++) {
                df.removeRow(0);
            }
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                String sql2 = "select cusid,cusname from customers where cusid = '" + rs.getString(2) + "' ";
                ResultSet rs2 = MyConn.search(sql2);
                while (rs2.next()) {
                    v.add(rs2.getString(1) + " - " + rs2.getString(2));
                }
                String sql3 = "select sid,sfirstname,slastname from staff where sid = '" + rs.getString(5) + "' ";
                ResultSet rs3 = MyConn.search(sql3);
                while (rs3.next()) {
                    v.add(rs3.getString(1) + " - " + rs3.getString(2) + " " + rs3.getString(3));
                }
                v.add(rs.getString(6));
                String discountPercentage = rs.getDouble(6) * 100 / rs.getDouble(7) + "";
                v.add(discountPercentage.substring(0, 3) + " %");
                v.add(rs.getString(7));
                df.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4KeyReleased(KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyReleased

    private void PrintActionPerformed(ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        try {
            final PrintingFrame frame = new PrintingFrame();
            frame.setVisible(true);
            frame.title.setText("Print Document - Sales Report ");
            ActionListener listner = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        InputStream loc = null;
                        if (frame.PrintType.getSelectedIndex() == 0) {
                            loc = getClass().getResourceAsStream("/Reports/SalesReport2.jrxml");
                        } else {
                            loc = getClass().getResourceAsStream("/Reports/SalesReport.jrxml");
                         }
                        HashMap map = new HashMap();
                        SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
                        map.put("FirstDate", format.format(dateChooserCombo1.getSelectedDate().getTime()));
                        map.put("SecondDate", format.format(dateChooserCombo2.getSelectedDate().getTime()));
                        map.put("totalIncome", Total.getText());
                        map.put("totalDiscount", Discount.getText());
                        JasperPrint jp = JasperFillManager.fillReport(JasperCompileManager.compileReport(loc), map, (new JRTableModelDataSource(jTable1.getModel())));
                        JasperViewer.viewReport(jp, false);
                    } catch (Exception ex) {
                    }

                }
            };
            frame.jButton2.addActionListener(listner);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SalesReport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Discount;
    private javax.swing.JButton Print;
    private javax.swing.JButton Search;
    private javax.swing.JLabel Total;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    public void printJob() {
    }
}
